- generic [active] [ref=e1]:
  - complementary [ref=e2]:
    - generic [ref=e4]:
      - generic [ref=e8]: JP
      - generic [ref=e9]: Picard OS
    - navigation [ref=e10]:
      - link "Dashboard" [ref=e11] [cursor=pointer]:
        - /url: /
        - img [ref=e12]
        - text: Dashboard
      - link "XODUS" [ref=e17] [cursor=pointer]:
        - /url: /xodus
        - img [ref=e18]
        - text: XODUS
      - link "Daily Log" [ref=e20] [cursor=pointer]:
        - /url: /daily
        - img [ref=e21]
        - text: Daily Log
      - link "Projects" [ref=e24] [cursor=pointer]:
        - /url: /projects
        - img [ref=e25]
        - text: Projects
      - link "Fitness" [ref=e27] [cursor=pointer]:
        - /url: /fitness
        - img [ref=e28]
        - text: Fitness
      - generic [ref=e30]: Tools
      - link "Stack" [ref=e31] [cursor=pointer]:
        - /url: /stack
        - img [ref=e32]
        - text: Stack
      - link "Voice" [ref=e35] [cursor=pointer]:
        - /url: /voice
        - img [ref=e36]
        - text: Voice
      - link "Uploads" [ref=e39] [cursor=pointer]:
        - /url: /uploads
        - img [ref=e40]
        - text: Uploads
    - generic [ref=e43]:
      - generic [ref=e44]:
        - generic [ref=e45]: Recovery
        - generic [ref=e46]: 74%
      - paragraph [ref=e49]: HRV 52ms · RHR 52bpm
  - main [ref=e51]:
    - generic [ref=e52]:
      - generic [ref=e54]:
        - paragraph [ref=e55]: Daily Check-In
        - heading "Daily Log" [level=1] [ref=e56]
        - paragraph [ref=e57]: Saturday, May 9
      - generic [ref=e58]:
        - generic [ref=e59]:
          - paragraph [ref=e60]: Body
          - generic [ref=e61]:
            - generic [ref=e62]:
              - generic [ref=e63]:
                - generic [ref=e65]: Body Weight
                - generic [ref=e66]:
                  - spinbutton [ref=e67]
                  - generic [ref=e68]: lb
              - generic [ref=e69]:
                - generic [ref=e71]: Sleep
                - generic [ref=e72]:
                  - spinbutton [ref=e73]
                  - generic [ref=e74]: hrs
            - generic [ref=e75]:
              - generic [ref=e77]: Steps Today
              - generic [ref=e78]:
                - spinbutton [ref=e79]
                - generic [ref=e80]: steps
        - generic [ref=e81]:
          - paragraph [ref=e82]: Nutrition
          - generic [ref=e83]:
            - generic [ref=e84]:
              - generic [ref=e85]:
                - generic [ref=e87]: Calories
                - generic [ref=e88]:
                  - spinbutton [ref=e89]
                  - generic [ref=e90]: kcal
              - generic [ref=e91]:
                - generic [ref=e92]:
                  - generic [ref=e93]: Cal Target
                  - generic [ref=e94]: default 2500
                - generic [ref=e95]:
                  - spinbutton [ref=e96]
                  - generic [ref=e97]: kcal
            - generic [ref=e98]:
              - generic [ref=e99]:
                - generic [ref=e101]: Protein
                - generic [ref=e102]:
                  - spinbutton [ref=e103]
                  - generic [ref=e104]: g
              - generic [ref=e105]:
                - generic [ref=e106]:
                  - generic [ref=e107]: Protein Target
                  - generic [ref=e108]: default 180g
                - generic [ref=e109]:
                  - spinbutton [ref=e110]
                  - generic [ref=e111]: g
            - generic [ref=e112]:
              - generic [ref=e114]: Water
              - generic [ref=e115]:
                - spinbutton [ref=e116]
                - generic [ref=e117]: glasses
        - generic [ref=e118]:
          - paragraph [ref=e119]: Screen Time
          - generic [ref=e120]:
            - generic [ref=e121]:
              - generic [ref=e122]:
                - generic [ref=e123]: Total Screen Time
                - generic [ref=e124]: target 2h
              - generic [ref=e125]:
                - spinbutton [ref=e126]
                - generic [ref=e127]: hours
            - generic [ref=e128]:
              - generic [ref=e130]: Instagram Time
              - generic [ref=e131]:
                - spinbutton [ref=e132]
                - generic [ref=e133]: hours
        - generic [ref=e134]:
          - paragraph [ref=e135]: Habits
          - generic [ref=e136]:
            - generic [ref=e137]:
              - generic [ref=e139]: Smoked Today
              - generic [ref=e140]:
                - button "Yes" [ref=e141]
                - button "No" [ref=e142]
            - generic [ref=e143]:
              - generic [ref=e145]: Drank Alcohol Today
              - generic [ref=e146]:
                - button "Yes" [ref=e147]
                - button "No — streak continues" [ref=e148]
        - generic [ref=e149]:
          - paragraph [ref=e150]: Mental
          - generic [ref=e151]:
            - generic [ref=e152]:
              - generic [ref=e154]: Mood / Energy (1–5)
              - generic [ref=e155]:
                - button "1" [ref=e156]
                - button "2" [ref=e157]
                - button "3" [ref=e158]
                - button "4" [ref=e159]
                - button "5" [ref=e160]
            - generic [ref=e161]:
              - generic [ref=e163]: Confidence (1–10)
              - generic [ref=e164]:
                - button "1" [ref=e165]
                - button "2" [ref=e166]
                - button "3" [ref=e167]
                - button "4" [ref=e168]
                - button "5" [ref=e169]
                - button "6" [ref=e170]
                - button "7" [ref=e171]
                - button "8" [ref=e172]
                - button "9" [ref=e173]
                - button "10" [ref=e174]
            - generic [ref=e175]:
              - generic [ref=e177]: Notes
              - textbox "What's on your mind today?" [ref=e178]
        - generic [ref=e179]:
          - button "Save Log" [ref=e180]
          - paragraph [ref=e181]: Saved locally · XODUS reads this to personalize your daily brief
  - button "Open Next.js Dev Tools" [ref=e187] [cursor=pointer]:
    - img [ref=e188]