// Phase 1: Scan the ChatGPT export ZIP without unpacking it.
// Writes Full_Archive_Map.md and a skeleton ChatGPT_Memory_Index.md.

import fs from "node:fs";
import path from "node:path";
import JSZip from "jszip";
import { ZIP_PATH, OUT_ROOT, OUTPUT_FILES } from "./config.ts";
import type { ArchiveEntryInfo } from "./types.ts";

const MEDIA_EXT = new Set([".png",".jpg",".jpeg",".webp",".gif",".wav",".mp3",".m4a",".heic"]);
const DOC_EXT   = new Set([".pdf",".docx",".xlsx",".ods",".txt",".md",".csv",".sav",".html"]);

function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 ** 3) return `${(n / 1024 / 1024).toFixed(1)} MB`;
  return `${(n / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

async function main(): Promise<void> {
  if (!fs.existsSync(ZIP_PATH)) {
    console.error(`[scan] ZIP not found at ${ZIP_PATH}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT_ROOT, { recursive: true });

  const zipStat = fs.statSync(ZIP_PATH);
  console.log(`[scan] Reading ZIP header: ${fmtBytes(zipStat.size)}`);

  // JSZip will hold a directory of entries in memory but only buffers the
  // central directory + per-entry metadata until you request an entry's data.
  const buf = await fs.promises.readFile(ZIP_PATH);
  const zip = await JSZip.loadAsync(buf, { checkCRC32: false });

  const entries: ArchiveEntryInfo[] = [];
  zip.forEach((relPath, entry) => {
    if (entry.dir) return;
    const ext = path.extname(relPath).toLowerCase();
    // _data is internal to JSZip but provides uncompressedSize/compressedSize.
    const meta = (entry as unknown as { _data?: { uncompressedSize?: number; compressedSize?: number } })._data ?? {};
    entries.push({
      path: relPath,
      size: meta.uncompressedSize ?? 0,
      compressedSize: meta.compressedSize ?? 0,
      isJsonShard: /^conversations(?:-\d+)?\.json$/i.test(relPath),
      isMedia: MEDIA_EXT.has(ext),
      ext,
    });
  });

  const shards   = entries.filter(e => e.isJsonShard).sort((a, b) => a.path.localeCompare(b.path));
  const media    = entries.filter(e => e.isMedia);
  const docs     = entries.filter(e => !e.isMedia && !e.isJsonShard && DOC_EXT.has(e.ext));
  const otherJson = entries.filter(e => !e.isJsonShard && e.ext === ".json");

  // ----- Full_Archive_Map.md -----
  const lines: string[] = [];
  lines.push("# Full Archive Map — ChatGPT Export");
  lines.push("");
  lines.push("> Generated by `scripts/chatgpt-memory-import/scan-export.ts`. The raw ZIP is **not** copied into the repo.");
  lines.push("");
  lines.push(`- **ZIP path:** \`${ZIP_PATH}\``);
  lines.push(`- **ZIP size (compressed):** ${fmtBytes(zipStat.size)}`);
  lines.push(`- **Total entries:** ${entries.length}`);
  lines.push(`- **Conversation shards:** ${shards.length}`);
  lines.push(`- **Loose JSON files:** ${otherJson.length}`);
  lines.push(`- **Documents (pdf/docx/csv/etc):** ${docs.length}`);
  lines.push(`- **Media (images/audio):** ${media.length}`);
  lines.push("");
  lines.push("## Conversation Shards");
  lines.push("");
  lines.push("| Shard | Size |");
  lines.push("|---|---|");
  for (const e of shards) lines.push(`| \`${e.path}\` | ${fmtBytes(e.size)} |`);
  lines.push("");
  lines.push("## Other JSON Files");
  lines.push("");
  if (otherJson.length === 0) lines.push("_(none)_");
  for (const e of otherJson) lines.push(`- \`${e.path}\` — ${fmtBytes(e.size)}`);
  lines.push("");
  lines.push("## Documents (attached files)");
  lines.push("");
  if (docs.length === 0) lines.push("_(none)_");
  for (const e of docs) lines.push(`- \`${e.path}\` — ${fmtBytes(e.size)}`);
  lines.push("");
  lines.push("## Media");
  lines.push("");
  lines.push(`Total media entries: **${media.length}**. Not enumerated here (too noisy). See raw ZIP for inventory.`);
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("- `chat.html` is intentionally skipped in later phases — the JSON shards contain the same content in structured form.");
  lines.push("- Attached documents (PDFs, DOCX, etc.) are catalogued here for reference but not text-extracted by this pipeline.");
  lines.push("- Media files are catalogued by count only; this pipeline ingests text memory, not images/audio.");
  lines.push("");

  fs.writeFileSync(path.join(OUT_ROOT, OUTPUT_FILES.archiveMap), lines.join("\n"), "utf8");
  console.log(`[scan] Wrote ${OUTPUT_FILES.archiveMap}`);

  // ----- ChatGPT_Memory_Index.md skeleton -----
  const idx: string[] = [];
  idx.push("# ChatGPT Memory Index");
  idx.push("");
  idx.push(`_Generated ${new Date().toISOString()}._`);
  idx.push("");
  idx.push("Curated outputs from the local ChatGPT export ingestion pipeline.");
  idx.push("");
  idx.push("## Inventory");
  idx.push("");
  idx.push(`- [Archive map](./${OUTPUT_FILES.archiveMap})`);
  idx.push(`- [Raw excerpt index](./${OUTPUT_FILES.rawIndex})`);
  idx.push("");
  idx.push("## Memory categories");
  idx.push("");
  for (const [key, file] of Object.entries(OUTPUT_FILES)) {
    if (file === OUTPUT_FILES.index || file === OUTPUT_FILES.archiveMap || file === OUTPUT_FILES.rawIndex) continue;
    idx.push(`- [${key}](./${file})`);
  }
  idx.push("");
  idx.push("## How to use this");
  idx.push("");
  idx.push("1. Skim **Possible_Outdated_Info.md** and **Conflicts_To_Review.md** first — these are the highest-signal review items.");
  idx.push("2. Treat each category file as a candidate set of Obsidian/Picard-OS memories.");
  idx.push("3. Approved items can be copied from `obsidian-staging/` into the real Obsidian vault.");
  idx.push("");
  fs.writeFileSync(path.join(OUT_ROOT, OUTPUT_FILES.index), idx.join("\n"), "utf8");
  console.log(`[scan] Wrote ${OUTPUT_FILES.index}`);

  console.log("[scan] Done.");
}

main().catch((err) => {
  console.error("[scan] FAILED", err);
  process.exit(1);
});
